spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/store
    driver-class-name: org.mariadb.jdbc.Driver
    username: store
    password: 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop

    jwt:
      secret: anjaehyunUsingForTest #원래는 공개하면 안됨.